# SPDX-FileCopyrightText: SUSE LLC
# SPDX-License-Identifier: Apache-2.0

header:
  comment: on-failure
  license:
    spdx-id: Apache-2.0
    copyright-owner: SUSE LLC
    software-name: trento-project.github.io
    content: |
      SPDX-FileCopyrightText: SUSE LLC
      SPDX-License-Identifier: Apache-2.0
  paths-ignore:
    - "**/*.md"
    - "**/*.svg"
    - ".github/CODEOWNERS"
    - ".github/dependabot.yml"
    - ".tool-versions"
    - "LICENSE"
    - "themes/**"
